// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using NetTopologySuite.Geometries;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EF6_WebApi.Models
{
    public partial class GetCoursesByStudentIdResult
    {
        public int? courseid { get; set; }
        public string coursename { get; set; }
        public Geometry Location { get; set; }
        public int? TeacherId { get; set; }
    }
}
