// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF6_WebApi.Models
{
    [Table("Standard")]
    public partial class Standard
    {
        public Standard()
        {
            Students = new HashSet<Student>();
            Teachers = new HashSet<Teacher>();
        }

        [Key]
        public int StandardId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string StandardName { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Description { get; set; }

        [InverseProperty("Standard")]
        public virtual ICollection<Student> Students { get; set; }
        [InverseProperty("Standard")]
        public virtual ICollection<Teacher> Teachers { get; set; }
    }
}