// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF6_WebApi.Models
{
    [Table("StudentAddress")]
    public partial class StudentAddress
    {
        [Key]
        [Column("StudentID")]
        public int StudentId { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string Address1 { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string Address2 { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string City { get; set; }
        [Required]
        [StringLength(50)]
        [Unicode(false)]
        public string State { get; set; }

        [ForeignKey("StudentId")]
        [InverseProperty("StudentAddress")]
        public virtual Student Student { get; set; }
    }
}