// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF6_WebApi.Models
{
    [Table("Student")]
    public partial class Student
    {
        public Student()
        {
            StudentCourses = new HashSet<StudentCourse>();
        }

        [Key]
        [Column("StudentID")]
        public int StudentId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string StudentName { get; set; }
        public int? StandardId { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }

        [ForeignKey("StandardId")]
        [InverseProperty("Students")]
        public virtual Standard Standard { get; set; }
        [InverseProperty("Student")]
        public virtual StudentAddress StudentAddress { get; set; }
        [InverseProperty("Student")]
        public virtual ICollection<StudentCourse> StudentCourses { get; set; }
    }
}