// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace EF6_WebApi.Models
{
    [Table("Teacher")]
    public partial class Teacher
    {
        public Teacher()
        {
            Courses = new HashSet<Course>();
        }

        [Key]
        public int TeacherId { get; set; }
        [StringLength(50)]
        [Unicode(false)]
        public string TeacherName { get; set; }
        public int? StandardId { get; set; }
        public int? TeacherType { get; set; }

        [ForeignKey("StandardId")]
        [InverseProperty("Teachers")]
        public virtual Standard Standard { get; set; }
        [InverseProperty("Teacher")]
        public virtual ICollection<Course> Courses { get; set; }
    }
}